apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  selector:
    app: react
    tier: client
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: fastapi
spec:
  type: ClusterIP
  selector:
    component: fastapi
  ports:
    - port: 4200
      targetPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      component: fastapi
  template:
    metadata:
      labels:
        component: fastapi
    spec:
      containers:
        - name: cowin-sub-server
          image: asia.gcr.io/sanpj-fun-gamers/cowin-notification-subscriber/cowin-sub-server:latest
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "1000m"
            requests:
              cpu: "400m"
          livenessProbe:
            httpGet:
              path: /health
              port: 4200
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 4200
            initialDelaySeconds: 30
            periodSeconds: 5
          ports:
            - containerPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
      tier: client
  template:
    metadata:
      labels:
        app: react
        tier: client
    spec:
      containers:
        - name: cowin-sub-client
          image: asia.gcr.io/sanpj-fun-gamers/cowin-notification-subscriber/cowin-sub-client:latest
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "1000m"
            requests:
              cpu: "400m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
          ports:
            - containerPort: 80