version: "3"
services:
    client:
        container_name: cowin_sub_client
        build: ./client
        depends_on:
            - db
            - server
        ports:
            - 80:80
        networks:
            - cowin_sub_network
        environment:
            NODE_ENV: production
    server:
        container_name: cowin_sub_server
        build: ./server
        env_file:
            - db.env
        command: ["python", "app.py"]
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
        networks:
            - cowin_sub_network
        ports:
            - 4200:4200
    db:
        image: postgres:13-alpine
        container_name: cowin_sub_db
        env_file:
            - db.env
        restart: always
        volumes:
            - ./db_data:/var/lib/postgresql/data
        networks:
            - cowin_sub_network
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 5s
            retries: 5

networks:
    cowin_sub_network:
        driver: bridge